name: publish-pyspao

on:
  push:
    tags:
       - 'v*'

jobs:

  linux-wheels:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux_2_28_x86_64
    steps:
     - uses: actions/checkout@v3
       with:
         submodules: recursive
     - name: Build wheels
       run: |
         bash .github/workflows/build-wheels.sh
     - uses: actions/upload-artifact@v3
       with:
         name: linux-wheels
         path: wheelhouse/

  osx-wheels:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
     - uses: actions/checkout@v3
       with:
         submodules: recursive
     - uses: actions/setup-python@v4
       with:
         python-version: ${{ matrix.python-version }}
     - name: Build wheels
       run: |
         python3 -m venv venv3
         source venv3/bin/activate
         make build
     - uses: actions/upload-artifact@v3
       with:
         name: osx-${{ matrix.python-version }}-wheel
         path: dist/
