name: test-pyspoa

on: [push]

jobs:

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Test ${{ matrix.os }} binding
        run: |
          python3 -m venv venv3
          source venv3/bin/activate
          make test

  linux-wheels:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux_2_28_x86_64
    steps:
     - uses: actions/checkout@v3
       with:
          submodules: recursive
     - name: Build wheels
       run: |
         bash .github/workflows/build-wheels.sh

  osx-wheels:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
     - uses: actions/checkout@v3
       with:
          submodules: recursive
     - uses: actions/setup-python@v4
       with:
         python-version: ${{ matrix.python-version }}
     - name: Build wheels
       run: |
         python3 -m venv venv3
         source venv3/bin/activate
         make test
